"""baseline

Revision ID: 027cc30f39e4
Revises: 
Create Date: 2017-01-02 13:15:04.396982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '027cc30f39e4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('root_cause',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bug',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('root_cause_id', sa.Integer(), nullable=False),
    sa.Column('bug_tracker_url', sa.String(), nullable=True),
    sa.Column('who', sa.String(), nullable=True),
    sa.Column('when', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['root_cause_id'], ['root_cause.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bug_tracker_url')
    )
    op.create_index(op.f('ix_bug_root_cause_id'), 'bug', ['root_cause_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bug_root_cause_id'), table_name='bug')
    op.drop_table('bug')
    op.drop_table('root_cause')
    # ### end Alembic commands ###
